import { useEffect, useRef, useState } from 'react';
import { Bell, ChevronDown, Menu, UserRound, LogOut } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Member } from '../../types';
export function Header({ title, member, onMenu, onLogout }: { title: string; member: Member; onMenu: () => void; onLogout: () => void }) {
  const [panel, setPanel] = useState<'profile' | 'notifications' | null>(null);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const close = (event: MouseEvent) => { if (!ref.current?.contains(event.target as Node)) setPanel(null); }; const escape = (event: KeyboardEvent) => { if (event.key === 'Escape') setPanel(null); }; document.addEventListener('mousedown', close); document.addEventListener('keydown', escape); return () => { document.removeEventListener('mousedown', close); document.removeEventListener('keydown', escape); }; }, []);
  return <header className="header"><div className="flex items-center gap-3"><button className="icon-button menu-toggle" onClick={onMenu} aria-label="Open navigation"><Menu size={22} /></button><h1 className="text-base font-semibold">{title}</h1><span className="header-context">Member portal</span></div><div ref={ref} className="relative flex items-center gap-3 sm:gap-5"><button className="icon-button" aria-label="Notifications" aria-expanded={panel === 'notifications'} onClick={() => setPanel(panel === 'notifications' ? null : 'notifications')}><Bell size={20} /></button><span className="h-7 w-px bg-border" /><button className="profile-button" aria-expanded={panel === 'profile'} onClick={() => setPanel(panel === 'profile' ? null : 'profile')}><span className="avatar">{member.firstName[0]}{member.lastName[0]}</span><span className="hidden text-left sm:block"><span className="block text-sm font-semibold">{member.firstName} {member.lastName}</span><span className="block text-xs text-muted">Business Member</span></span><ChevronDown size={15} className="text-muted" /><span className="sr-only">Profile options</span></button>{panel && <div className="header-popover">{panel === 'notifications' ? <><h2 className="font-semibold">Notifications</h2><p className="mt-3 text-sm leading-6 text-muted">You’re all caught up. Member updates will appear here.</p></> : <><p className="mb-3 break-all text-xs text-muted">{member.email}</p><Link className="dropdown-item" to="/dashboard/profile" onClick={() => setPanel(null)}><UserRound size={16} />My profile</Link><button className="dropdown-item w-full" onClick={() => { setPanel(null); onLogout(); }}><LogOut size={16} />Logout</button></>}</div>}</div></header>;
}

