import { ArrowLeft, BookOpen, CalendarDays, Clock, MapPin } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { memberService, formatDate } from '../services/memberService';
import { MembershipCard } from '../components/MembershipCard';
import { EventCard } from '../components/EventCard';
function Intro({ title, text }: { title: string; text: string }) { return <div className="page-intro"><div><p className="eyebrow mb-2">BNAK MEMBER PORTAL</p><h2>{title}</h2><p>{text}</p></div></div>; }
export function ProfilePage() { const member = memberService.getMember(); return <><Intro title="My profile" text="Your member information, all in one place." /><section className="panel p-6 sm:p-8"><div className="flex items-center gap-4 border-b border-border pb-6"><span className="avatar avatar-large">{member.firstName[0]}{member.lastName[0]}</span><div><h2 className="text-xl font-semibold">{member.firstName} {member.lastName}</h2><p className="mt-1 text-sm text-muted">{member.membershipNumber} · Business Member</p></div></div><dl className="profile-details">{[['Email address', member.email], ['Phone number', member.phone], ['Business name', member.businessName], ['County', member.county]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="notice">These details come from your membership registration. Contact BNAK to request corrections.</p></section></>; }
export function MembershipPage() { return <><Intro title="Your membership" text="Connected to a community that supports your business." /><MembershipCard member={memberService.getMember()} membership={memberService.getMembership()} /><p className="notice mt-5">Renewal opens 30 days before expiry. Use the Payments page to pay with M-PESA.</p></>; }
export function EventsPage() { return <><Intro title="Connect. Learn. Grow." text="Discover upcoming events for the BNAK member community." /><div className="grid gap-5 md:grid-cols-2">{memberService.getEvents().map(event => <div key={event.id} className="panel px-6"><EventCard event={event} /></div>)}</div><p className="notice mt-5">No events have been published yet.</p></>; }
export function EventDetailsPage() { const { eventId } = useParams(); const event = memberService.getEvents().find(item => item.id === eventId); if (!event) return <NotFoundPage />; return <><Link className="text-link mb-6" to="/dashboard/events"><ArrowLeft size={16} />Back to events</Link><Intro title={event.name} text={event.category} /><article className="panel p-6 sm:p-8"><div className="flex flex-wrap gap-5 text-sm text-muted"><span className="flex items-center gap-2"><CalendarDays size={18} />{formatDate(event.date)}</span><span className="flex items-center gap-2"><Clock size={18} />{event.time}</span><span className="flex items-center gap-2"><MapPin size={18} />{event.location}</span></div><h2 className="mt-8 font-semibold">About this event</h2><p className="mt-3 max-w-3xl leading-7 text-muted">{event.description}</p><p className="notice mt-6">Sample event · Registration is not available yet.</p></article></>; }
export function ResourcesPage() { return <><Intro title="Member resources" text="Practical support for your business journey." /><div className="grid gap-5 md:grid-cols-3">{[['Business guides', 'Practical guidance for starting and running your business.'], ['Member handbook', 'Learn about your membership and the BNAK community.'], ['Association updates', 'News and updates from across the association.']].map(([title, description]) => <article className="panel p-6" key={title}><span className="icon-tile"><BookOpen size={22} /></span><h2 className="mt-5 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-muted">{description}</p><span className="mt-6 inline-block rounded-full bg-surface px-3 py-1 text-xs text-muted">Coming soon</span></article>)}</div></>; }
export function NotFoundPage() { return <><Intro title="Page not found" text="This page is not available in the member portal." /><Link className="primary-button" to="/dashboard">Back to overview</Link></>; }
